### ISSUE TITLE
Le partage

### ISSUE THREAD

**Issue by ezioms** [yanterrien/photobrouille#1]
peut-on le modifier puis le partager sur freebox ?

**Comment by yanterrien** [comment]
Drôle de question.
"Peut-on le modifier ?" Oui, comme tout ce qui est public sur Github
"puis le partager sur freebox ?" Je ne comprends pas bien cette partie de la question. Si vous voulez partir de mon code, et le modifier pour corriger un bug, je me ferai un plaisir de le corriger dans l'appli qui est actuellement sur la freebox, je pourrai même rajouter votre nom dans la description si ça vous fait plaisir. Par compte, si vous le modifier pour vous en servir de base pour faire une nouvelle application, personne ne vous empêche de le publier sur la Freebox sous un autre nom.
